[package]
name = "polars_ols"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_ols"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["extension-module", "abi3-py310"] }
pyo3-polars = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
polars = { version = "*", features = ["performant", "lazy", "ndarray"]}
ndarray = { version = "*"}
ndarray-rand = {version = "*"}
ndarray-linalg = {version = "*"}
faer = {version = "*"}
faer-ext = {version = "*", features = ["ndarray"]}
num-traits = { version = "*" }

[target.'cfg(target_os = "macos")'.dependencies]
ndarray = { version = "*", features = ["blas"] }
ndarray-linalg = { version = "*", features = ["openblas"]}
blas-src = { version = "*", features = ["openblas"] }
openblas-src = { version = "*", features = ["static"] }

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
ndarray = { version = "*", features = ["blas"] }
ndarray-linalg = { version = "*", features = ["intel-mkl"]}

[target.'cfg(all(unix, target_arch = "x86"))'.dependencies]
ndarray-linalg = { version = "*", features = ["netlib"]}

[profile.dev.package.faer]
opt-level = 3
