[package]
name = "polars_ols"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_ols"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["extension-module", "abi3-py310"] }
pyo3-polars = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
polars = { version = "*", features = ["performant", "lazy", "ndarray"]}
ndarray = { version = "*", features = ["blas"]}
ndarray-rand = {version = "*"}
faer = {version = "*"}
faer-ext = {version = "*", features = ["ndarray"]}
num-traits = { version = "*" }
approx = {version = "*" }

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
blas-sys = {version = "*"}

#[target.'cfg(all(target_os = "linux", not(target_arch = "x86_64")))'.dependencies]
#ndarray = { version = "*", features = ["matrixmultiply-threading"]}

[dev-dependencies]
ndarray-linalg = {version = "*"}

[profile.dev.package.faer]
opt-level = 3
