[package]
name = "polars-ols"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_ols"
crate-type= ["cdylib"]

[dependencies]
openssl = {version = "*", features = ["vendored"]}
openssl-sys = {version = "*", features = ["vendored"]}
pyo3 = { version = "*", features = ["extension-module", "abi3-py38"] }
pyo3-polars = { version = "*", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
polars = { version = "*", features = ["performant", "lazy", "ndarray"]}
ndarray = { version = "*", features=["rayon", "blas"] }
#blas-src = { version = "*", features = ["openblas"] }
#openblas-src = { version = "*", features = ["cblas"] }
ndarray-rand = {version = "*"}
ndarray-linalg = {version = "*", features = ["openblas-static"]}
faer = {version = "*"}
faer-ext = {version = "*", features = ["ndarray"]}
rayon = {version = "*"}

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }

[profile.dev.package.faer]
opt-level = 3
